<?php

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 */
$productPrice = $this->helper(\Magento\Catalog\Helper\Data::class)->getProduct()->getFinalPrice();
$helper = $this->helper(\Sega\ChristmasCoins\Helper\Data::class);
$shouldDisplayMessage = $helper->DisplayChristmasCoinsMessage();
$mightBeReceivedCoins = $helper->calculateChristmasCoinsAmount($productPrice);

if ($shouldDisplayMessage) {
    echo __('You will receive %1 coins for purchasing this product.', $mightBeReceivedCoins);
}
