<?php

$viewModel = $block->getData('view_model');
$collection = $viewModel->getRandomProducts();

?>

<div>
    <ul>
        <?php foreach ($collection as $item): ?>

            <li class="randomProductItem">
                <a class="randomProductImage" href="<?= $item->getProductUrl() ?>">
                    <img src="<?= $this->helper('Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'catalog/product'.$item->getImage('thumbnail') ?>" alt="prod">
                </a>
                <div class="randomProductInfo">
                    <a href="<?= $item->getProductUrl() ?>"><span class="randomProductName"><?= $item->getName() ?></span></a>
                    <span class="randomProductPrice"><?= '$' . intval($item->getPrice()) ?></span>
                </div>
            </li>

        <?php endforeach; ?>
    </ul>
</div>
