<?php
/**
 * @var \Meetanshi\Extension\Block\Edit $block
 * @var \Magento\Framework\Escaper $escaper
 */

$item = $block->getFrontPost();
?>
<legend class="legend">
    <span><?= __('Edit post') ?></span>
</legend>
<br>
<form class="form form-edit-post"
      method="post"
      action="<?= $escaper->escapeUrl($block->getUrl('extension/index/save')) ?>"
      id="form-validate"
      autocomplete="off"
      data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <input type="number"
               id="id"
               name="id"
               class="input-text"
               hidden
               value="<?= $escaper->escapeHtml($item->getID()) ?>">
        <div class="field">
            <label class="label" for="name">
                <span><?= __('Name') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="name"
                       name="name"
                       class="input-text"
                       value="<?= $escaper->escapeHtml($item->getName()) ?>"
                       data-validate="{'required-entry':true}" >
            </div>
        </div>
        <div class="field">
            <label class="label" for="email">
                <span><?= __('Email') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="email"
                       name="email"
                       class="input-text"
                       value="<?= $escaper->escapeHtml($item->getEmail()) ?>"
                       data-validate="{'required-entry':true}" >
            </div>
        </div>
        <div class="field">
            <label class="label" for="telephone">
                <span><?= __('Telephone') ?></span>
            </label>
            <div class="control">
                <input type="number"
                       id="telephone"
                       name="telephone"
                       min="0"
                       class="input-number"
                       value="<?= $escaper->escapeHtml($item->getTelephone()) ?>"
                       data-validate="{'required-number':true}">
            </div>
        </div>
        <div class="field">
            <label class="label" for="notebook">
                <span><?= __('Notebook') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="notebook"
                       name="notebook"
                       value="<?= $escaper->escapeHtml($item->getNotebook()) ?>"
                       data-validate="{'required-entry':true}" >
            </div>
        </div>
        <div class="field">
            <label class="label" for="description">
                <span><?= __('Description') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       id="description"
                       name="description"
                       class="input-text"
                       value="<?= $escaper->escapeHtml($item->getDescription()) ?>"
                       data-validate="{'required-entry':true}" >
            </div>
        </div>

        <div class="primary">
            <button type="submit" class="action primary">
                <span><?= __('Save') ?></span>
            </button>
        </div>
    </fieldset>
</form>
