<?php
$data = $block->getAllData();

?>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend">Fill Detail</legend>
                <fieldset class="fieldset row">
                    <?php if ($data->getId()): ?>
                        <input type="hidden" name="id" value="<?php echo $data->getId(); ?>">
                    <?php endif ?>
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title">Name</label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="<?php echo $data->getName() ?>" class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title">Email</label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="<?php echo $data->getEmail() ?>"
                                       class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title">Telephone</label>
                            <div class="control">
                                <input name="telephone" id="telephone" title="Telephone"
                                       value="<?php echo $data->getTelephone() ?>" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title">Notebook</label>
                            <div class="control">
                                <input name="notebook" id="notebook" title="notebook"
                                       value="<?php echo $data->getNotebook() ?>" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title">Description</label>
                            <div class="control">
                                <input name="description" id="description" title="description"
                                       value="<?php echo $data->getDescription() ?>" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
