<?php
/**
 * Category view template
 *
 * @var \Meetanshi\Extension\Block\Index $block
 * @var \Magento\Framework\Escaper $escaper
 */
$collection = $block->getCollection();
?>
<legend class="legend">
    <span><?= __('Orders') ?></span>
</legend>
<br>
<a class="action primary" href="<?= $escaper->escapeUrl($block->getUrl('extension/index/create')) ?>">Add new Entity</a>
<table>
    <tr>
        <th><?= __('ID') ?></th>
        <th><?= __('Name') ?></th>
        <th><?= __('Email') ?></th>
        <th><?= __('Telephone') ?></th>
        <th><?= __('Notebook') ?></th>
        <th><?= __('Description') ?></th>
        <th><?= __('Created At') ?></th>
        <th colspan="2"><?= __('Actions') ?></th>
    </tr>
    <?php foreach ($collection as $item): ?>
        <tr>
            <td><?= $escaper->escapeHtml($item->getId()) ?></td>
            <td><?= $escaper->escapeHtml($item->getName()) ?></td>
            <td><?= $escaper->escapeHtml($item->getEmail()) ?></td>
            <td><?= $escaper->escapeHtml($item->getTelephone()) ?></td>
            <td><?= $escaper->escapeHtml($item->getNotebook()) ?></td>
            <td><?= $escaper->escapeHtml($item->getDescription()) ?></td>
            <td><?= $escaper->escapeHtml($item->getCreatedAt()) ?></td>
            <td><a href="<?= $escaper->escapeUrl($block->getUrl('extension/index/edit').'id/'.$item->getId()); ?>" class="action primary">Edit</a></td>
            <td><a href="<?= $escaper->escapeUrl($block->getUrl('extension/index/delete').'?id='.$item->getId()); ?>" class="action primary">Delete</a></td>
        </tr>
    <?php endforeach; ?>
</table>
